# name: NPM Publish

# on:
#     release:
#         types: [created]

# jobs:
#     build:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v2
#             - uses: actions/setup-node@v1
#               with:
#                   node-version: 14
#             - run: |
#                   cd ./scripts/npm-publish
#                   npm ci
#             - run: |
#                   cd ./javascript-typescript-wrapper
#                   npm ci
#                   npm start --prefix ../scripts/npm-publish
#                   npm publish
#                   git config user.name github-actions
#                   git config user.email github-actions@github.com
#                   git add .
#                   git commit -m 'updated version'
#                   git push
#               env:
#                   NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}


name: NPM publish CD workflow

on:
  release:
    # This specifies that the build will be triggered when we publish a release
    types: [published]

jobs:
  build:

    # Run on latest version of ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # "ref" specifies the branch to check out.
        # "github.event.release.target_commitish" is a global variable and specifies the branch the release targeted
        ref: ${{ github.event.release.target_commitish }}
    # install Node.js
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: |
       cd ./javascript-typescript-wrapper
       npm ci
       git config user.name github-actions
       git config user.email github-actions@github.com
       npm version ${{ github.event.release.tag_name }}
       npm run build
       npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    - run: git push
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
