name: NPM Publish

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: |
                  cd ./scripts/npm-publish
                  npm ci
            - run: |
                  cd ./javascript-typescript-wrapper
                  npm ci
                  npm start --prefix ../scripts/npm-publish
                  npm publish
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m 'updated version'
                  git push
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
