name: NPM Publish

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: |
                  cd ./scripts/npm-publish
                  npm ci
            - run: |
                  cd ./javascript-typescript-wrapper
                  npm start --prefix ../scripts/npm-publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
